version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        options: --reload
    image: mdapy
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    restart: on-failure
